Apple's M1 mac device 사용을 고려한 device 할당

In [1]:
import torch

if torch.backends.mps.is_available():
    device = torch.device('mps') # Apple's M1
else:
    device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')

In [2]:
device

device(type='mps')

In [3]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device=device)
points_gpu

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='mps:0')

In [4]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]]) # tensor on CPU
points.to(device)

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='mps:0')

In [5]:
points = 2 * points # CPU
points_gpu = 2 * points.to(device) # GPU

In [6]:
points_gpu = points_gpu + 4 # still running on GPU (no more CPU engage)
points_gpu

tensor([[20.,  8.],
        [24., 16.],
        [12.,  8.]], device='mps:0')

In [7]:
points_cpu = points_gpu.to('cpu') # GPU -> CPU
points_cpu

tensor([[20.,  8.],
        [24., 16.],
        [12.,  8.]])

In [8]:
points_cpu = points_gpu.cpu() # GPU -> CPU
points_cpu

tensor([[20.,  8.],
        [24., 16.],
        [12.,  8.]])

In [9]:
points_cpu_long = points_gpu.to('cpu', dtype=torch.long) # dtype : float -> long
points_cpu_long

tensor([[20,  8],
        [24, 16],
        [12,  8]])

In [10]:
points_cpu_short = points_gpu.to('cpu', dtype=torch.short) # dtype : float -> short
points_cpu_short

tensor([[20,  8],
        [24, 16],
        [12,  8]], dtype=torch.int16)